### ISSUE TITLE
Issue #8

### ISSUE THREAD

**Issue by DarkSuffer01** [sertchan/Discord-Scraper#11]
![Issue](https://user-images.githubusercontent.com/107288467/187206737-da4d2691-1b1b-4f84-b896-04ea917ea781.png)
Uhh, After 18% scraping it stops and gave me this kind of error..

**Comment by sertchan** [comment]
try with vpn

**Comment by DarkSuffer01** [comment]
> try with vpn

Nevermind. Account Issues again, Discord can't hold or scrape on my main.

**Comment by sertchan** [comment]
👍🏻👍🏻👍🏻👍🏻👍🏻
