### ISSUE TITLE
`Issue token it is a string`

### ISSUE THREAD

**Issue by Labs22** [sertchan/Discord-Scraper#12]
Hello, good evening. I hope everything it is ok with you.

Soi I was trying to make this work and doing some test and I have some problem.

I know how to get the token but  so when I copy to the envi.example

I have tried only with the token, token with simple quote and token + double quote and every single tried I got a issue

"Token it is a string" and I cant make this work.

I'm not a programmer so how I suppose to put the token?

Do I need to give a single space after "=" this?

Can you help me?

And thank you for your contribution. 

Best regards

**Comment by sertchan** [comment]
first rename env.example file to .env (delete the .example part) then you mustn't put token in  ("TOKEN") or ('TOKEN') format. Just put it like TOKEN=ABCDEFG. I think this answer would helpful for you have a good day.
