### ISSUE TITLE
[Suggestion] Bio Scraper

### ISSUE THREAD

**Issue by Akkey5783** [sertchan/Discord-Scraper#2]
I would like to see Bio Scraper added to the program.

**Comment by sertchan** [comment]
Im going to rewrite this project with go language then i will add such more features like bio scrapeing , account creation date etc.

**Comment by sertchan** [comment]
also sorry for late answer

**Comment by sertchan** [comment]
Okay new update i will not rewrite code in go cause i dont wanna lost time for 2 ms diffrence so yeah i will try to add this feature if api supports it

**Comment by sertchan** [comment]
It is not possiable to rewrite code in go rust etc. cause of discord res api limits and bio scraper and banner scraper impossiable due disocrd js api limitions.
