### ISSUE TITLE
sa

### ISSUE THREAD

**Issue by Wapperlx** [sertchan/Discord-Scraper#6]
proje ne ise yarıyor

**Comment by sertchan** [comment]
?

**Comment by sertchan** [comment]
![image](https://user-images.githubusercontent.com/53477192/183408195-8a9c5e59-b906-48e4-9965-b1d5df0bb585.png)

**Comment by sertchan** [comment]
kisacasi belirli bir serverdeki tum memberlerin ulasilabilir neleri varsa indririyor. Lutfen yildizlamayi unutma projeyi!
