### ISSUE TITLE
Another Issue

### ISSUE THREAD

**Issue by DarkSuffer01** [sertchan/Discord-Scraper#7]
So, The "node ." Wasn't working. It just says 'TOKEN INVALID'
So I tried "npm start" It worked,
![image](https://user-images.githubusercontent.com/107288467/183427008-6e458f73-41f0-4eef-ab89-12cdfb8a5e98.png)
But this happend.

This is the same issue a few days ago, How am i gonna scrape username and pfp if this issue won't fix.

**Comment by sertchan** [comment]
Can you try to change your password on github it reset's your user token so node . might work with that

**Comment by sertchan** [comment]
and it is pretty intresting i have never seen guild members timeout in my whole coding experience you can try an vpn for network

**Comment by DarkSuffer01** [comment]
I tried reseting my password, But it still didn't work.

**Comment by DarkSuffer01** [comment]
> and it is pretty intresting i have never seen guild members timeout in my whole coding experience you can try an vpn for network

I don't have any vpn, I can't find any free vpn.

**Comment by DarkSuffer01** [comment]
Can i try using replit instead?

**Comment by sertchan** [comment]
just change your ip to another location any service allowed

**Comment by sertchan** [comment]
Okay that could be something about your account. If you have an alt account just use it instead of you account also delete project from locale and reclone it from git. then create your .env file using .env.example. you can invite your alt account to guild which is you want to scrape 👍🏻

**Comment by DarkSuffer01** [comment]
> Okay that could be something about your account. If you have an alt account just use it instead of you account also delete project from locale and reclone it from git. then create your .env file using .env.example. you can invite your alt account to guild which is you want to scrape 👍🏻

Thanks, It works very well. My token was nuked, Maybe that was the problem. it cause error

**Comment by DarkSuffer01** [comment]
> Okay that could be something about your account. If you have an alt account just use it instead of you account also delete project from locale and reclone it from git. then create your .env file using .env.example. you can invite your alt account to guild which is you want to scrape 👍🏻

By the way, How to scrape all of the users?

**Comment by sertchan** [comment]
we cannot scrape all of the users cause of discord api limitions but you could use opcode 8 but it also have limitions thats the problem why we cannot scrape all of the users

**Comment by sertchan** [comment]
> > Okay that could be something about your account. If you have an alt account just use it instead of you account also delete project from locale and reclone it from git. then create your .env file using .env.example. you can invite your alt account to guild which is you want to scrape 👍🏻
> 
> Thanks, It works very well. My token was nuked, Maybe that was the problem. it cause error

Im glad to hear that. Good lock with that script!
